---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: services
  label: Services
  create: documents
  match: "**/*"
  exclude: "*.json"
  templates:
  - service
- type: directory
  path: products
  label: Products
  create: documents
  match: "**/*"
  exclude: "*.json"
  templates:
  - service
- type: directory
  path: testimonials
  label: Testimonials
  create: documents
  match: "**/*"
  exclude: "*.json"
  templates:
  - testimonial
- type: directory
  path: faqs
  label: FAQs
  create: documents
  match: "**/*"
  exclude: "*.json"
  templates:
  - faq
- type: heading
  label: Content
- type: document
  path: _includes/components/footer.njk
  label: Footer
upload_dir: ''
public_path: _includes/assets/documents
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
